name: Anime Score Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.10.0

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Generate timestamp tag
      run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.15.0
      with:
        context: .
        push: true
        tags: |
          stellatezero/anime-score-web:latest
          stellatezero/anime-score-web:${{ env.TIMESTAMP }}

    # - name: executing remote ssh commands using password
    #   uses: appleboy/ssh-action@v1
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: root
    #     password: ${{ secrets.PASSWORD }}
    #     port: ${{ secrets.PORT }}
    #     script: bash /opt/anime-score-docker/run.sh
